sudo: required

dist: trusty

language: python

services:
  - docker

matrix:
  include:
    - env: TF_TAG=1.0.1     TD_TEST_SCIPY=0 TD_TEST_GPU=0
    - env: TF_TAG=1.0.1     TD_TEST_SCIPY=1 TD_TEST_GPU=0
    - env: TF_TAG=1.0.1-py3 TD_TEST_SCIPY=0 TD_TEST_GPU=0

install:
  - docker pull tensorflow/tensorflow:$TF_TAG

script: docker run -t --rm -v `pwd`:/root/tfdeploy -w /root/tfdeploy -e TD_TEST_SCIPY=$TD_TEST_SCIPY -e TD_TEST_GPU=$TD_TEST_GPU tensorflow/tensorflow:$TF_TAG python -m unittest tests
